apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  ports:
    - port: 3000
  selector:
    app: my-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: my-app:9
        ports:
        - containerPort: 3000
#        livenessProbe:
#          httpGet:
#            port: 3000
#            path: /healthz
#          initialDelaySeconds: 3
#          periodSeconds: 3
        env:
          - name: NEXT_PUBLIC_MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NEXT_PUBLIC_MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NEXT_PUBLIC_CONFIG_MAP_KEY
            valueFrom:
              configMapKeyRef:
                name: main
                key: configMapKey
          - name: NEXT_PUBLIC_MY_SECRET
            valueFrom:
              secretKeyRef:
                name: main
                key: mySecret
