name: Apply manifests

on:
  push:
    tags:
      - v*

env:
  SOPS_VERSION: 3.7.3
  GCP_PROJECT: k8s-cicd-353408
  GCP_ZONE: asia-northeast1-a

defaults:
  run:
    working-directory: manifests

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cdk8s-cli
        run: |
          npm i -g cdk8s-cli

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Install age
        run: |
          curl -L -o age.tar.gz https://dl.filippo.io/age/latest?for=linux/amd64
          tar xf age.tar.gz
          sudo mv age/age /usr/local/bin
          sudo mv age/age-keygen /usr/local/bin

      - name: Install sops
        run: |
          curl -L -o sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v${SOPS_VERSION}.linux.amd64
          chmod 755 sops
          sudo mv sops /usr/local/bin

      - name: Login to GCP
        uses: google-github-actions/auth@ceee102ec2387dd9e844e01b530ccd4ec87ce955 # v0.8.0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up GCP Cloud SDK
        uses: google-github-actions/setup-gcloud@877d4953d2c70a0ba7ef3290ae968eb24af233bb # v0.6.0

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@0a5f57b989b81d2725178cda257a00acf7d6bb5f # 0.7.0
        with:
          cluster_name: main
          location: ${{ env.GCP_ZONE }}

      - name: Decrypt secrets
        env:
          SOPS_AGE_KEY: ${{ secrets.AGE_KEY }}
        run: |
          cd values
          sops -d secrets-staging.enc.env > secrets-staging.env

      - name: Generate manifests
        env:
          VALUES_FILE: values/values-staging.env
          SECRETS_FILE: values/secrets-staging.env
          DOCKER_REGISTRY: gcr.io/k8s-cicd-353408
        run: |
          npm run compile
          npm run synth

      - name: Clear secrets
        run: |
          rm values/secrets-staging.env

      - name: Apply manifests
        run: |
          kubectl apply -f dist/
