name: Apply manifests

on:
  push:
    tags:
      - v*

env:
  SOPS_VERSION: 3.7.3
  GOOGLE_PROJECT: k8s-cicd
  GOOGLE_ZONE: asia-northeast1-a

defaults:
  run:
    working-directory: manifests

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cdk8s-cli
        run: |
          npm i -g cdk8s-cli

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Install age
        run: |
          curl -L -o age.tar.gz https://dl.filippo.io/age/latest?for=linux/amd64
          tar xf age.tar.gz
          sudo mv age/age /usr/local/bin
          sudo mv age/age-keygen /usr/local/bin

      - name: Install sops
        run: |
          curl -L -o sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v${SOPS_VERSION}.linux.amd64
          chmod 755 sops
          sudo mv sops /usr/local/bin

      - id: auth
        uses: google-github-actions/auth@ceee102ec2387dd9e844e01b530ccd4ec87ce955 # v0.8.0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@877d4953d2c70a0ba7ef3290ae968eb24af233bb # v0.6.0

      - name: Setup GCP project
        run: |
          gcloud config set project ${GOOGLE_PROJECT}
          gcloud config set compute/zone ${GOOGLE_ZONE}
          gcloud container clusters get-credentials main

      - name: Install kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl

      - name: Decrypt secrets
        env:
          SOPS_AGE_KEY: ${{ secrets.AGE_KEY }}
        run: |
          cd values
          sops -d secrets-staging.enc.env > secrets-staging.env

      - name: Generate manifests
        env:
          VALUES_FILE: values/values-staging.env
          SECRETS_FILE: values/secrets-staging.env
        run: |
          npm run compile
          npm run synth

      - name: Clear secrets
        run: |
          rm values/secrets-staging.env

      - name: apply manifests
        run: |
          kubectl apply -f dist/
