name: Apply manifests

on:
  push:
    tags:
      - v*

env:
  SOPS_VERSION: 3.7.3

defaults:
  run:
    working-directory: manifests

jobs:
  generate-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cdk8s-cli
        run: |
          npm i -g cdk8s-cli

      - name: Install age
        run: |
          curl -L -o age.tar.gz https://dl.filippo.io/age/latest?for=linux/amd64
          tar xf age.tar.gz
          sudo mv age/age /usr/local/bin
          sudo mv age/age-keygen /usr/local/bin

      - name: Install sops
        run: |
          curl -L -o sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v${SOPS_VERSION}.linux.amd64
          chmod 755 sops
          sudo mv sops /usr/local/bin

      - name: Decrypt secrets
        env:
          SOPS_AGE_KEY: ${{ secrets.AGE_KEY }}
        run: |
          cd values
          sops -d secrets-staging.enc.env > secrets-staging.env

      - name: Generate manifests
        env:
          VALUES_FILE: values/values-staging.env
          SECRETS_FILE: values/secrets-staging.env
        run: |
          npm run compile
          cdk8s synth

      - name: Clear secrets
        run: |
          rm values/secrets-staging.env
