name: Apply manifests

on:
  push:
    tags:
      - v*

env:
  SOPS_VERSION: 3.7.3

defaults:
  run:
    working-directory: manifests

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cdk8s-cli
        run: |
          npm i -g cdk8s-cli

      - name: Install age
        run: |
          apt install age

      - name: Install sops
        run: |
          curl -L -o sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v${SOPS_VERSION}.linux.amd64
          mv sops /usr/local/bin

  generate-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Decrypt secrets
        run: |
          cd values
          sops -d secrets-staging.enc.env > secrets-staging.env

      - name: Generate manifests
        run: |
          VALUES_FILE=values/values-staging.env SECRETS_FILE=values/secrets-staging.env cdk8s synth

      - name: Clear secrets
        run: |
          rm values/secrets-staging.env
